Login
GabrielP410/TPCRUD pull request #18
Opened 2023-12-15 08:33 UTC by guadavillarreal

Modificaciones en la pag del login para evitar que se superponga los elementos y no tenga problemas con dispositivos pequeños, creación de una hoja de estilo para la misma

2023-12-15 09:38 UTC, eugenioxcornejo requested changes
creo que esos dos pueden ser conlficto, el resto parece ok

2023-12-15 09:38 UTC, eugenioxcornejo commented on css/login.css
> +    text-decoration: none;
esta etiqueta puede generar conflicto usa el nombre de un contenedor comun y la etiqueta "a"

2023-12-15 09:38 UTC, eugenioxcornejo commented on css/login.css
> +  form a:hover {
mismo

2023-12-16 17:30 UTC, ivanbaldiviezo commented
Falta actualizar el navar y footer, y corregir lo que marca Eugenio

2023-12-16 17:30 UTC, closed without merging